'use client'
import { useEffect, useState, type FormEvent } from 'react'
import type { Locale } from '@/lib/i18n'
type Comment={id:string;name:string;body:string}
const api=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3000/v1'
export function Comments({slug,locale}:{slug:string;locale:Locale}) {
 const ar=locale==='ar';const [rows,setRows]=useState<Comment[]>([]);const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState(false);const [retry,setRetry]=useState(0);const [pending,setPending]=useState(false);const [sent,setSent]=useState(false);const [error,setError]=useState(false)
 useEffect(()=>{const controller=new AbortController();setLoading(true);setLoadError(false);fetch(`${api}/posts/${encodeURIComponent(slug)}/comments?locale=${locale}&page=${page}&limit=10`,{signal:controller.signal}).then(res=>{if(!res.ok)throw new Error();return res.json()}).then(data=>{setRows(data.data);setTotal(data.total)}).catch(e=>{if(e.name!=='AbortError')setLoadError(true)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[slug,locale,page,retry])
 async function submit(event:FormEvent<HTMLFormElement>) {event.preventDefault();if(pending)return;const form=event.currentTarget;const data=new FormData(form);setPending(true);setError(false);try{const response=await fetch(`${api}/posts/${encodeURIComponent(slug)}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:data.get('name'),body:data.get('body'),website:data.get('website'),locale})});if(!response.ok)throw new Error();setSent(true);form.reset()}catch{setError(true)}finally{setPending(false)}}
 return <section className="post-comments" aria-labelledby="comments-title"><h2 id="comments-title">{ar?'التعليقات':'Comments'}</h2>{loading?<p>{ar?'جارٍ التحميل…':'Loading comments…'}</p>:loadError?<p role="alert">{ar?'تعذر تحميل التعليقات.':'Could not load comments.'} <button onClick={()=>setRetry(v=>v+1)}>{ar?'إعادة المحاولة':'Retry'}</button></p>:<>{rows.length===0&&<p>{ar?'كن أول من يشارك بتعليق.':'Be the first to leave a comment.'}</p>}{rows.map(comment=><article key={comment.id}><h3>{comment.name}</h3><p className="whitespace-pre-wrap break-words">{comment.body}</p></article>)}{total>10&&<div className="post-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>{ar?'السابق':'Previous'}</button><span>{page}</span><button disabled={page*10>=total} onClick={()=>setPage(p=>p+1)}>{ar?'التالي':'Next'}</button></div>}</>}
 <form className="post-comment-form" onSubmit={submit}><h3>{ar?'شارك بتعليق':'Leave a comment'}</h3><p>{ar?'التعليقات عامة وتُنشر بعد المراجعة. يرجى عدم مشاركة بيانات طبية شخصية.':'Comments are public and reviewed before publishing. Please don’t share personal medical information.'}</p><label htmlFor="comment-name">{ar?'الاسم':'Name'}</label><input id="comment-name" name="name" required minLength={2} maxLength={80} autoComplete="name"/><label htmlFor="comment-body">{ar?'التعليق':'Comment'}</label><textarea id="comment-body" name="body" required minLength={3} maxLength={2000} rows={4}/><div hidden><label htmlFor="comment-website">Website</label><input id="comment-website" name="website" tabIndex={-1} autoComplete="off"/></div><button type="submit" disabled={pending}>{pending?(ar?'جارٍ الإرسال…':'Sending…'):(ar?'إرسال التعليق':'Submit comment')}</button>{sent&&<p role="status">{ar?'تم استلام تعليقك وهو الآن قيد المراجعة.':'Your comment was received and is awaiting review.'}</p>}{error&&<p role="alert">{ar?'تعذر إرسال التعليق. تحقق من البيانات أو حاول بعد قليل.':'Could not send your comment. Check your details or try again shortly.'}</p>}</form></section>
}
