'use client'
import { useState } from 'react'
import { Building2, Search, ArrowUpRight } from 'lucide-react'
export type Partner={id:string;name:string;category:string;logoUrl:string|null;websiteUrl:string|null}
export function InsuranceDirectory({partners,locale}:{partners:Partner[];locale:'ar'|'en'}) {
 const ar=locale==='ar';const [query,setQuery]=useState('');const [category,setCategory]=useState('all')
 const labels:Record<string,string>={all:ar?'جميع الشركاء':'All partners',insurance:ar?'شركات التأمين':'Insurance companies',company:ar?'الشركات':'Corporate partners',authority:ar?'الهيئات والمؤسسات':'Organizations'}
 const filtered=partners.filter(p=>(category==='all'||p.category===category)&&p.name.toLocaleLowerCase(locale).includes(query.trim().toLocaleLowerCase(locale)))
 return <><div className="insurance-tools"><div className="insurance-tabs" role="group" aria-label={ar?'نوع التعاقد':'Partner category'}>{Object.entries(labels).filter(([key])=>key==='all'||partners.some(p=>p.category===key)).map(([key,label])=><button key={key} type="button" aria-pressed={key===category} onClick={()=>setCategory(key)}>{label}</button>)}</div><label className="post-search"><span className="sr-only">{ar?'ابحث عن شركة':'Search partners'}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?'ابحث عن جهة التعاقد…':'Search a partner…'}/><Search size={19}/></label></div><p className="insurance-count" role="status">{filtered.length} {ar?'جهة تعاقد':'partners'}</p><div className="insurance-partners" key={category}>{filtered.map(partner=><article className="insurance-partner" key={partner.id}><div className="insurance-partner-logo">{partner.logoUrl?<img src={partner.logoUrl} alt="" loading="lazy"/>:<Building2 size={40} strokeWidth={1.2}/>}</div><span>{labels[partner.category]}</span><h2>{partner.name}</h2>{partner.websiteUrl&&/^https?:\/\//i.test(partner.websiteUrl)&&<a href={partner.websiteUrl} target="_blank" rel="noopener noreferrer">{ar?'الموقع الرسمي':'Official website'}<ArrowUpRight size={16}/></a>}</article>)}</div>{!filtered.length&&<div className="hospital-directory-empty"><h2>{ar?'لا توجد جهات للعرض':'No partners to display'}</h2><p>{ar?'جرّب اسماً آخر أو تواصل معنا للتحقق من جهة تعاقدك.':'Try another name or contact our team to check your partner.'}</p>{(query||category!=='all')&&<button onClick={()=>{setQuery('');setCategory('all')}}>{ar?'مسح الفلاتر':'Clear filters'}</button>}</div>}</>
}
