import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Plus, ArrowLeft, Loader2, MessageSquare, Eye, Pencil } from 'lucide-react'
import { api } from '@/api/client'
import { useI18n } from '@/lib/i18n'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { RichTextEditor } from '@/components/shared/richtext-editor'
import { ImageInput } from '@/components/shared/image-input'
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog'

const empty = { slug:'', type:'article', titleAr:'', titleEn:'', excerptAr:'', excerptEn:'', contentAr:'', contentEn:'', categoryAr:'', categoryEn:'', authorAr:'', authorEn:'', seoTitleAr:'', seoTitleEn:'', seoDescriptionAr:'', seoDescriptionEn:'', coverUrl:'', status:'draft', commentsEnabled:true }
type Post = typeof empty & {id:string; updatedAt:string}
type Page<T> = {data:T[];total:number;page:number;limit:number}
function useCopy() { const {dir}=useI18n(); return (ar:string,en:string)=>dir==='rtl'?ar:en }
function Pager({page,total,onChange}:{page:number;total:number;onChange:(p:number)=>void}) {const l=useCopy();return <div className="flex items-center justify-end gap-3"><Button variant="outline" disabled={page<=1} onClick={()=>onChange(page-1)}>{l('السابق','Previous')}</Button><span>{page} / {Math.max(1,Math.ceil(total/12))}</span><Button variant="outline" disabled={page*12>=total} onClick={()=>onChange(page+1)}>{l('التالي','Next')}</Button></div>}

export function PostsPage() {
 const l=useCopy(); const [page,setPage]=useState(1); const [q,setQ]=useState(''); const [deleting,setDeleting]=useState<Post|null>(null);const cache=useQueryClient()
 const query=useQuery({queryKey:['posts',page,q],queryFn:()=>api<Page<Post>>(`/posts/admin/?page=${page}&limit=12&q=${encodeURIComponent(q)}`)})
 const remove=useMutation({mutationFn:(id:string)=>api(`/posts/admin/${id}`,{method:'DELETE'}),onSuccess:()=>{setDeleting(null);void cache.invalidateQueries({queryKey:['posts']})}})
 return <div className="space-y-5 p-4 lg:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{l('المقالات والأخبار','Articles & news')}</h1><p className="mt-1 text-sm text-muted-foreground">{l('إدارة المدونة والأخبار بالعربية والإنجليزية','Manage the bilingual blog and hospital news')}</p></div><div className="flex gap-2"><Button variant="outline" render={<Link to="/content/comments"/>}><MessageSquare className="size-4"/>{l('التعليقات','Comments')}</Button><Button render={<Link to="/content/posts/new"/>}><Plus className="size-4"/>{l('إضافة منشور','New post')}</Button></div></div>
 <Input aria-label={l('بحث','Search posts')} placeholder={l('ابحث عن عنوان…','Search titles…')} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} className="max-w-md"/>
 {query.isPending?<Loader2 className="animate-spin"/>:query.isError?<p role="alert">{query.error.message}</p>:<><div className="divide-y rounded-xl border">{query.data.data.length===0?<p className="p-8 text-center">{l('لا توجد منشورات. أضف أول منشور.','No posts yet. Create your first post.')}</p>:query.data.data.map(post=><div key={post.id} className="flex flex-wrap items-center justify-between gap-4 p-4"><Link to={`/content/posts/${post.id}`} className="min-w-0 flex-1"><h2 className="font-semibold">{l(post.titleAr,post.titleEn)}</h2><p className="mt-1 text-sm text-muted-foreground">{post.type==='article'?l('مقال / مدونة','Article / blog'):l('خبر','News')} · {post.status==='published'?l('منشور','Published'):post.status==='archived'?l('مؤرشف','Archived'):l('مسودة','Draft')}</p></Link><Button variant="outline" render={<Link to={`/content/posts/${post.id}`}/>}>{l('تعديل','Edit')}</Button><Button variant="ghost" onClick={()=>{remove.reset();setDeleting(post)}}>{l('حذف','Delete')}</Button></div>)}</div><Pager page={page} total={query.data.total} onChange={setPage}/></>}
 <AlertDialog open={!!deleting} onOpenChange={open=>!open&&!remove.isPending&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{l('حذف المنشور؟','Delete this post?')}</AlertDialogTitle><AlertDialogDescription>{l('سيتم حذف المنشور وتعليقاته نهائياً. يمكنك أرشفته من المحرر بدلاً من ذلك.','This permanently deletes the post and its comments. You can archive it from the editor instead.')}</AlertDialogDescription></AlertDialogHeader>{remove.isError&&<p role="alert">{remove.error.message}</p>}<AlertDialogFooter><AlertDialogCancel disabled={remove.isPending}>{l('إلغاء','Cancel')}</AlertDialogCancel><AlertDialogAction disabled={remove.isPending} onClick={e=>{e.preventDefault();if(deleting)remove.mutate(deleting.id)}}>{l('حذف','Delete')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
}

export function PostEditPage() {
 const {id}=useParams();const l=useCopy();const query=useQuery({queryKey:['post',id],queryFn:()=>api<Post>(`/posts/admin/${id}`),enabled:id!=='new'})
 if(id!=='new'&&query.isPending)return <div className="p-8"><Loader2 className="animate-spin"/></div>
 if(id!=='new'&&query.isError)return <div className="space-y-4 p-8"><p role="alert">{query.error.message}</p><Button onClick={()=>void query.refetch()}>{l('إعادة المحاولة','Retry')}</Button><Link to="/content">{l('العودة','Back')}</Link></div>
 return <PostEditor key={id} post={id==='new'?undefined:query.data}/>
}
function PostEditor({post}:{post?:Post}) {
 const l=useCopy();const navigate=useNavigate();const cache=useQueryClient();const [form,setForm]=useState(()=>({...empty,...post,coverUrl:post?.coverUrl??''}));const [lang,setLang]=useState<'ar'|'en'>('ar');const [preview,setPreview]=useState(false);const [validation,setValidation]=useState('')
 const field=(key:keyof typeof empty,value:string|boolean)=>setForm(f=>({...f,[key]:value}))
 const suffix=lang==='ar'?'Ar':'En'
 const save=useMutation({mutationFn:()=>api<Post>(post?`/posts/admin/${post.id}`:'/posts/admin/',{method:post?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),onSuccess:()=>{void cache.invalidateQueries({queryKey:['posts']});void cache.invalidateQueries({queryKey:['post']});navigate('/content')}})
 return <div className="mx-auto max-w-7xl space-y-5 p-4 lg:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Button variant="outline" size="icon" render={<Link to="/content"/>} aria-label={l('العودة','Back')}><ArrowLeft className="size-4 rtl:rotate-180"/></Button><h1 className="text-2xl font-bold">{post?l('تعديل المنشور','Edit post'):l('منشور جديد','New post')}</h1></div><Button variant="outline" onClick={()=>setPreview(!preview)}>{preview?<Pencil className="size-4"/>:<Eye className="size-4"/>}{preview?l('المحرر','Editor'):l('معاينة','Preview')}</Button></div>
 <form onSubmit={e=>{e.preventDefault();setValidation('');if(!form.titleAr.trim()||!form.titleEn.trim()){setValidation(l('أدخل عنواناً بالعربية والإنجليزية.','Enter both Arabic and English titles.'));return}if(form.status==='published'&&(!form.contentAr.replace(/<[^>]*>/g,'').trim()||!form.contentEn.replace(/<[^>]*>/g,'').trim())){setValidation(l('أكمل محتوى اللغتين قبل النشر.','Complete both language versions before publishing.'));return}if(!save.isPending)save.mutate()}} className="grid items-start gap-6 lg:grid-cols-[1fr_320px]">
 <section className="min-w-0 space-y-5 rounded-xl border bg-card p-5"><div className="flex gap-2" role="group" aria-label={l('لغة المحتوى','Content language')}>{(['ar','en'] as const).map(v=><Button key={v} type="button" variant={v===lang?'default':'outline'} onClick={()=>setLang(v)} aria-pressed={lang===v}>{v==='ar'?'العربية':'English'}</Button>)}</div>
 {preview?<div dir={lang==='ar'?'rtl':'ltr'} className="space-y-4">{form.coverUrl&&<img src={form.coverUrl} alt="" className="max-h-80 w-full rounded-lg object-cover"/>}<h2 className="text-3xl font-bold">{form[`title${suffix}`]}</h2><p className="text-muted-foreground">{form[`excerpt${suffix}`]}</p><RichTextEditor key={`preview-${lang}`} value={form[`content${suffix}`]} onChange={()=>{}} dir={lang==='ar'?'rtl':'ltr'} readOnly/></div>:<div dir={lang==='ar'?'rtl':'ltr'} className="space-y-5">
 {(['title','excerpt','category','author'] as const).map(key=><div className="space-y-2" key={key}><Label htmlFor={`post-${key}`}>{({title:l('العنوان','Title'),excerpt:l('ملخص','Excerpt'),category:l('التصنيف','Category'),author:l('اسم الكاتب','Author name')})[key]}</Label>{key==='excerpt'?<Textarea id={`post-${key}`} maxLength={500} value={form[`excerpt${suffix}`]} onChange={e=>field(`excerpt${suffix}`,e.target.value)}/>:<Input id={`post-${key}`} maxLength={key==='title'?180:key==='category'?100:120} value={form[`${key}${suffix}`]} onChange={e=>field(`${key}${suffix}`,e.target.value)}/>}</div>)}
 <div className="space-y-2"><Label>{l('المحتوى','Content')}</Label><RichTextEditor key={lang} value={form[`content${suffix}`]} onChange={html=>field(`content${suffix}`,html)} dir={lang==='ar'?'rtl':'ltr'}/></div>
 <details className="rounded-lg border p-4"><summary className="font-semibold">{l('إعدادات محركات البحث','Search metadata')}</summary><div className="mt-4 space-y-3"><Label htmlFor="seo-title">{l('عنوان البحث','SEO title')}</Label><Input id="seo-title" maxLength={180} value={form[`seoTitle${suffix}`]} onChange={e=>field(`seoTitle${suffix}`,e.target.value)}/><Label htmlFor="seo-description">{l('وصف البحث','SEO description')}</Label><Textarea id="seo-description" maxLength={320} value={form[`seoDescription${suffix}`]} onChange={e=>field(`seoDescription${suffix}`,e.target.value)}/></div></details></div>}
 </section>
 <aside className="space-y-5 rounded-xl border bg-card p-5 lg:sticky lg:top-4"><h2 className="text-lg font-bold">{l('إعدادات النشر','Publishing')}</h2><div className="space-y-2"><Label htmlFor="post-slug">{l('رابط المنشور','URL slug')}</Label><Input id="post-slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={100} value={form.slug} onChange={e=>field('slug',e.target.value)} dir="ltr" placeholder="hospital-update"/></div>
 <div className="space-y-2"><Label htmlFor="post-type">{l('النوع','Type')}</Label><Select value={form.type} onValueChange={v=>v&&field('type',v)}><SelectTrigger id="post-type" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="article">{l('مقال / مدونة','Article / blog')}</SelectItem><SelectItem value="news">{l('خبر','News')}</SelectItem></SelectContent></Select></div>
 <div className="space-y-2"><Label htmlFor="post-status">{l('الحالة','Status')}</Label><Select value={form.status} onValueChange={v=>v&&field('status',v)}><SelectTrigger id="post-status" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">{l('مسودة','Draft')}</SelectItem><SelectItem value="published">{l('منشور','Published')}</SelectItem><SelectItem value="archived">{l('مؤرشف','Archived')}</SelectItem></SelectContent></Select></div>
 <div className="space-y-2"><Label>{l('صورة الغلاف','Cover image')}</Label><ImageInput value={form.coverUrl} onChange={url=>field('coverUrl',url)}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.commentsEnabled} onChange={e=>field('commentsEnabled',e.target.checked)}/>{l('السماح بالتعليقات بعد المراجعة','Allow moderated comments')}</label>
 <p className="text-xs text-muted-foreground">{l('يجب إكمال اللغتين قبل النشر. المسودات لا تظهر على الموقع.','Complete both languages before publishing. Drafts stay off the public website.')}</p>
 {(validation||save.isError)&&<p role="alert" className="text-sm text-destructive">{validation||save.error?.message}</p>}<Button type="submit" disabled={save.isPending} className="w-full">{save.isPending&&<Loader2 className="size-4 animate-spin"/>}{l('حفظ المنشور','Save post')}</Button></aside></form></div>
}

type Comment={id:string;name:string;body:string;status:string;titleAr:string;titleEn:string;locale:string}
export function PostCommentsPage() {
 const l=useCopy();const [status,setStatus]=useState('pending');const [page,setPage]=useState(1);const cache=useQueryClient()
 const query=useQuery({queryKey:['post-comments',status,page],queryFn:()=>api<Page<Comment>>(`/posts/admin/comments?status=${status}&page=${page}&limit=12`)})
 const update=useMutation({mutationFn:({id,status}:{id:string;status:string})=>api(`/posts/admin/comments/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})}),onSuccess:()=>void cache.invalidateQueries({queryKey:['post-comments']})})
 return <div className="space-y-5 p-4 lg:p-6"><Link to="/content">{l('العودة للمنشورات','Back to posts')}</Link><h1 className="text-2xl font-bold">{l('مراجعة التعليقات','Comment moderation')}</h1><div className="flex gap-2">{['pending','approved','rejected'].map(s=><Button key={s} variant={s===status?'default':'outline'} onClick={()=>{setStatus(s);setPage(1)}}>{s==='pending'?l('قيد المراجعة','Pending'):s==='approved'?l('منشور','Approved'):l('مرفوض','Rejected')}</Button>)}</div>{update.isError&&<p role="alert">{update.error.message}</p>}{query.isPending?<Loader2 className="animate-spin"/>:query.isError?<p role="alert">{query.error.message}</p>:<>{query.data.data.length===0&&<p className="rounded-lg border p-8 text-center">{l('لا توجد تعليقات هنا.','No comments here.')}</p>}{query.data.data.map(comment=><article key={comment.id} className="space-y-3 rounded-lg border p-5"><p className="text-sm text-muted-foreground">{l(comment.titleAr,comment.titleEn)}</p><h2 className="font-semibold">{comment.name}</h2><p className="whitespace-pre-wrap break-words" dir={comment.locale==='ar'?'rtl':'ltr'}>{comment.body}</p><div className="flex gap-2"><Button disabled={update.isPending||status==='approved'} onClick={()=>update.mutate({id:comment.id,status:'approved'})}>{l('نشر','Approve')}</Button><Button variant="outline" disabled={update.isPending||status==='rejected'} onClick={()=>update.mutate({id:comment.id,status:'rejected'})}>{l('إخفاء / رفض','Reject / hide')}</Button></div></article>)}<Pager page={page} total={query.data.total} onChange={setPage}/></>}</div>
}
